# Generated by Django 3.2.6 on 2021-08-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='card',
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categ', to='rod.category'),
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
